### PR TITLE
Add DB2 Data Gate product 

### PR DESCRIPTION
**Pull request by pelletierkevin**
https://github.com/IBM/cp4d-deployment/issues/20

### CODE REVIEW

**Comment by satyamodi** [comment]
"null_resource.install_datagate," needs to be added in the "depends_on = " section of the 
"resource "null_resource" "install_dods" {" 
resource "null_resource" "install_spss" {

**Comment by pelletierkevin** [comment]
> "null_resource.install_datagate," needs to be added in the "depends_on = " section of the
> "resource "null_resource" "install_dods" {"
> resource "null_resource" "install_spss" {

Thanks I just added the changes

**Comment by ajiyos** [comment]
@pelletierkevin Please change the pull request target to shadow branch instead of master.

**Comment by pelletierkevin** [comment]
> @pelletierkevin Please change the pull request target to shadow branch instead of master.

@ajiyos Done.

**Comment by ajiyos** [comment]
@pelletierkevin I will create another issue to build the pipeline to verify install and functional test. Once the pipeline is successful, it will be merged with the master.

**Pull request merged**
